"""The Microsoft-ICS reading rules, pinned offline — against a REAL captured invitation.

Every byte of `MICROSOFT_INVITE` below was composed by a real Microsoft 365 tenant on 2026-08-24
and captured through an external mailbox (PR Vexa-ai/vexa#1320's rig), with the tenant/organizer
GUIDs and the passcode replaced. It is folded at 75 octets exactly as Exchange folded it, because
the folding is half of what these tests defend against.

That PR targeted an abandoned base and merged nowhere. Its rig needed a live tenant and there is
no M365 credential in the vault, so the rig is NOT ported — but its findings are product
knowledge, they live in `flows_integrations/outlook.py`, and this is their executable form.

The three findings, and what each one costs when it is not known:

  1. `LOCATION` is the literal string "Microsoft Teams Meeting" — it NEVER carries the join URL.
     A parser that reads LOCATION reports "no meeting link" and the invite is silently ignored.
  2. `DESCRIPTION` carries TWO different links and the FIRST one is the wrong one. Its "Join:"
     line holds the short form `/meet/<15 digits>`; the `19:meeting_…@thread.v2` form appears
     only after "System reference:". A first-match regex therefore yields A DIFFERENT IDENTIFIER
     FOR THE SAME MEETING than the `X-` property does — no error, a bot that joins nothing.
  3. `X-MICROSOFT-SKYPETEAMSPROPERTIES.cid` carries the thread id ALREADY DECODED, so the correct
     reader parses a JSON field and does no URL parsing at all.

Plus the one that is not about Teams: `\\n` inside an ICS TEXT value is two characters, and a URL
character class permitting `\\` runs past the link into the next line's prose.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from flows_integrations import outlook                                  # noqa: E402
from flows_integrations.mailbox import TEAMS_URL, parse_ics             # noqa: E402

THREAD = "19:meeting_MmRlNmQzNTQtZDdlZi00ODVlLWIwNTQtYTlkNzRmZTJhYTg4@thread.v2"
JOIN = ("https://teams.microsoft.com/l/meetup-join/"
        "19%3ameeting_MmRlNmQzNTQtZDdlZi00ODVlLWIwNTQtYTlkNzRmZTJhYTg4%40thread.v2/0"
        "?context=%7b%22Tid%22%3a%22705eee68-0000-0000-0000-000000000000%22%2c"
        "%22Oid%22%3a%22dca999d8-0000-0000-0000-000000000000%22%7d")

# Folded at 75 octets, CRLF, continuation lines starting with a single space — verbatim Exchange
# output shape. DTSTART pushed to 2030 so the parser's "a start in the past is a parse artifact"
# guard does not reject it; nothing else is altered.
MICROSOFT_INVITE = (
    "BEGIN:VCALENDAR\r\n"
    "METHOD:REQUEST\r\n"
    "PRODID:Microsoft Exchange Server 2010\r\n"
    "VERSION:2.0\r\n"
    "BEGIN:VTIMEZONE\r\n"
    "TZID:UTC\r\n"
    "END:VTIMEZONE\r\n"
    "BEGIN:VEVENT\r\n"
    "ORGANIZER;CN=Dmitry Grankin:mailto:organizer@example.onmicrosoft.com\r\n"
    "ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE:mailto:info@vexa\r\n"
    " .ai\r\n"
    "SUMMARY;LANGUAGE=en-US:Vexa rig probe\r\n"   # ;LANGUAGE — Google never writes one
    "DTSTART:20300824T162446Z\r\n"
    "DTEND:20300824T165446Z\r\n"
    "UID:040000008200E00074C5B7101A82E00800000000F38FB748E233DD01000000000000000010\r\n"
    " 0000001D89A04EE6AD1347A50A21B9171836C0\r\n"
    "CLASS:PUBLIC\r\n"
    "PRIORITY:5\r\n"
    "DTSTAMP:20260824T160448Z\r\n"
    "TRANSP:OPAQUE\r\n"
    "STATUS:CONFIRMED\r\n"
    "SEQUENCE:0\r\n"
    "LOCATION;LANGUAGE=en-US:Microsoft Teams Meeting\r\n"
    "DESCRIPTION;LANGUAGE=en-US:Generated by the Vexa M365 test rig.\\nMicrosoft Tea\r\n"
    " ms meeting\\nJoin: https://teams.microsoft.com/meet/373241627805208?p=HspUEOnQ\r\n"
    " K2jxCFVGhg\\nMeeting ID: 373 241 627 805 208\\nPasscode: XXXXXXXX\\nHelp: https:/\r\n"
    " /aka.ms/JoinTeamsMeeting?omkt=en-US\\nSystem reference: " + JOIN[:38] + "\r\n"
    " " + JOIN[38:] + "\\n____________\r\n"
    "X-MICROSOFT-ONLINEMEETINGINFORMATION:{\"OnlineMeetingChannelId\":null\\,\"OnlineM\r\n"
    " eetingProvider\":3}\r\n"
    "X-MICROSOFT-SKYPETEAMSMEETINGURL:" + JOIN[:42] + "\r\n"
    " " + JOIN[42:] + "\r\n"
    "X-MICROSOFT-SKYPETEAMSPROPERTIES:{\"cid\":\"" + THREAD + "\"\\,\"rid\":0\\,\"mid\":0\\,\r\n"
    " \"uid\":null\\,\"private\":true\\,\"type\":0}\r\n"
    "X-MICROSOFT-LOCATIONS:[{\"DisplayName\":\"Microsoft Teams Meeting\"\\,\"LocationUri\r\n"
    " \":\"\"}]\r\n"
    "X-MICROSOFT-DISALLOW-COUNTER:FALSE\r\n"
    "END:VEVENT\r\n"
    "END:VCALENDAR\r\n"
)


def test_unfolding_is_a_precondition_not_a_nicety():
    """Un-unfolded, the join URL is split across physical lines and matches truncated."""
    assert JOIN not in outlook._TEAMS_URL.findall(MICROSOFT_INVITE)
    assert JOIN in outlook._TEAMS_URL.findall(outlook.unfold_ics(MICROSOFT_INVITE))


def test_location_never_carries_the_join_url():
    """The single most likely wrong guess a parser author makes."""
    assert "LOCATION" not in outlook.ics_teams_evidence(MICROSOFT_INVITE)["join_urls"]
    assert "LOCATION" not in outlook.ics_teams_properties(MICROSOFT_INVITE)


def test_description_first_match_is_the_wrong_id():
    urls = outlook.ics_teams_evidence(MICROSOFT_INVITE)["join_urls"]["DESCRIPTION"]
    assert outlook.teams_native_id(urls[0]) == ("teams", "373241627805208")
    assert outlook.teams_native_id(urls[-1]) == ("teams", THREAD)


def test_thread_id_comes_from_the_json_property_without_url_parsing():
    ev = outlook.ics_teams_evidence(MICROSOFT_INVITE)
    assert ev["thread_id"] == THREAD
    assert ev["online_meeting_provider"] == 3         # teamsForBusiness


def test_x_property_is_the_canonical_url_and_parses_to_the_thread_id():
    props = outlook.ics_teams_properties(MICROSOFT_INVITE)
    assert props["X-MICROSOFT-SKYPETEAMSMEETINGURL"] == JOIN
    assert outlook.teams_native_id(props["X-MICROSOFT-SKYPETEAMSMEETINGURL"]) == ("teams", THREAD)


def test_description_url_stops_at_the_escaped_newline():
    """`\\n` inside an ICS TEXT value is a literal backslash-n; a URL character class that allows
    backslashes runs past the link into the next line's prose."""
    first = outlook.ics_teams_evidence(MICROSOFT_INVITE)["join_urls"]["DESCRIPTION"][0]
    assert first.endswith("?p=HspUEOnQK2jxCFVGhg")
    assert "\\" not in first


def test_the_products_own_teams_pattern_stops_there_too():
    """Not only the evidence reader: `mailbox.TEAMS_URL` is what admits a Teams invite, and it
    used to allow `\\` in the path. THIS is the assertion that pins the fix in the shipped code."""
    hit = TEAMS_URL.search(outlook.unfold_ics(MICROSOFT_INVITE))
    assert hit is not None
    assert "\\" not in hit.group(0)


def test_non_teams_input_is_reported_as_absent_not_guessed():
    assert outlook.ics_teams_evidence("") == {}
    assert outlook.ics_teams_evidence("BEGIN:VCALENDAR\r\nEND:VCALENDAR\r\n") == {}
    assert outlook.teams_native_id("https://meet.google.com/abc-defg-hij") is None
    assert outlook.teams_native_id("") is None
    assert outlook.teams_join_url("BEGIN:VCALENDAR\r\nEND:VCALENDAR\r\n") is None


def test_rfc2047_subject_decoding():
    """Exchange encodes any subject with a non-ASCII character; an em dash suffices."""
    assert outlook.decode_header_text(
        "=?Windows-1252?Q?Vexa_rig_=97_ICS_property_probe?=") == "Vexa rig \u2014 ICS property probe"
    assert outlook.decode_header_text("plain subject") == "plain subject"


# ── and now the product, end to end over the real invitation ─────────────────────────────────
def test_the_parser_admits_the_canonical_url_not_the_first_one_it_sees():
    """THE PORT'S POINT. `parse_ics` scans the event top-to-bottom; on this invitation that order
    is LOCATION (prose), then DESCRIPTION (the short-form id), then the X- property. Without the
    Microsoft-first rule the admitted URL is `/meet/373241627805208` — a different identifier for
    the same meeting, admitted with no error, and a bot dispatched at nothing."""
    ev = parse_ics(MICROSOFT_INVITE, "info@vexa.ai")
    assert ev is not None
    assert ev["url"] == JOIN
    assert outlook.teams_native_id(ev["url"]) == ("teams", THREAD)
    assert ev["organizer"] == "organizer@example.onmicrosoft.com"
    # `SUMMARY;LANGUAGE=en-US:` — `^SUMMARY:` matched nothing, so every Exchange invite was
    # titled "Meeting", and that title is the subject line of the mail we send back.
    assert ev["title"] == "Vexa rig probe"


def test_the_generic_scan_alone_would_have_taken_the_wrong_link():
    """The counter-proof, so the assertion above cannot pass for the wrong reason."""
    from flows_integrations.mailbox import _meeting_url
    generic = _meeting_url(outlook.unfold_ics(MICROSOFT_INVITE))
    assert generic is not None
    assert outlook.teams_native_id(generic) == ("teams", "373241627805208")
    assert generic != JOIN
