"""The Microsoft-ICS reading rules, pinned offline.

Every byte of MICROSOFT_INVITE below was captured from a REAL invitation composed by a
real Microsoft 365 tenant on 2026-08-24 (rig: `witness/m365_rig.py invite send` →
`gmail poll`), with the tenant/organizer GUIDs and the passcode replaced. It is folded at
75 octets exactly as Exchange folded it, because the folding is half of what these tests
are defending against.

The three findings these tests exist to keep true:

  1. LOCATION is the string "Microsoft Teams Meeting" — it NEVER carries the join URL.
  2. DESCRIPTION carries TWO different links, and the FIRST one is the short-form
     `/meet/<digits>` id, not the `19:meeting_…@thread.v2` the meeting-api wants.
  3. X-MICROSOFT-SKYPETEAMSPROPERTIES.cid carries the thread id already decoded, so the
     correct parser reads a JSON field and does no URL parsing at all.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "witness"))

import m365_rig as rig  # noqa: E402

THREAD = "19:meeting_MmRlNmQzNTQtZDdlZi00ODVlLWIwNTQtYTlkNzRmZTJhYTg4@thread.v2"
JOIN = ("https://teams.microsoft.com/l/meetup-join/"
        "19%3ameeting_MmRlNmQzNTQtZDdlZi00ODVlLWIwNTQtYTlkNzRmZTJhYTg4%40thread.v2/0"
        "?context=%7b%22Tid%22%3a%22705eee68-0000-0000-0000-000000000000%22%2c"
        "%22Oid%22%3a%22dca999d8-0000-0000-0000-000000000000%22%7d")

# Folded at 75 octets, CRLF, continuation lines starting with a single space — verbatim
# Exchange output shape.
MICROSOFT_INVITE = (
    "BEGIN:VCALENDAR\r\n"
    "METHOD:REQUEST\r\n"
    "PRODID:Microsoft Exchange Server 2010\r\n"
    "VERSION:2.0\r\n"
    "BEGIN:VTIMEZONE\r\n"
    "TZID:UTC\r\n"
    "END:VTIMEZONE\r\n"
    "BEGIN:VEVENT\r\n"
    "ORGANIZER;CN=Dmitry Grankin:mailto:organizer@example.onmicrosoft.com\r\n"
    "ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE:mailto:info@vexa\r\n"
    " .ai\r\n"
    "SUMMARY;LANGUAGE=en-US:Vexa rig \xe2\x80\x94 ICS property probe\r\n"
    "DTSTART:20260824T162446Z\r\n"
    "DTEND:20260824T165446Z\r\n"
    "UID:040000008200E00074C5B7101A82E00800000000F38FB748E233DD01000000000000000010\r\n"
    " 0000001D89A04EE6AD1347A50A21B9171836C0\r\n"
    "CLASS:PUBLIC\r\n"
    "PRIORITY:5\r\n"
    "DTSTAMP:20260824T160448Z\r\n"
    "TRANSP:OPAQUE\r\n"
    "STATUS:CONFIRMED\r\n"
    "SEQUENCE:0\r\n"
    "LOCATION;LANGUAGE=en-US:Microsoft Teams Meeting\r\n"
    "DESCRIPTION;LANGUAGE=en-US:Generated by the Vexa M365 test rig.\\nMicrosoft Tea\r\n"
    " ms meeting\\nJoin: https://teams.microsoft.com/meet/373241627805208?p=HspUEOnQ\r\n"
    " K2jxCFVGhg\\nMeeting ID: 373 241 627 805 208\\nPasscode: XXXXXXXX\\nHelp: https:/\r\n"
    " /aka.ms/JoinTeamsMeeting?omkt=en-US\\nSystem reference: " + JOIN[:38] + "\r\n"
    " " + JOIN[38:] + "\\n____________\r\n"
    "X-MICROSOFT-ONLINEMEETINGINFORMATION:{\"OnlineMeetingChannelId\":null\\,\"OnlineM\r\n"
    " eetingProvider\":3}\r\n"
    "X-MICROSOFT-SKYPETEAMSMEETINGURL:" + JOIN[:42] + "\r\n"
    " " + JOIN[42:] + "\r\n"
    "X-MICROSOFT-SKYPETEAMSPROPERTIES:{\"cid\":\"" + THREAD + "\"\\,\"rid\":0\\,\"mid\":0\\,\r\n"
    " \"uid\":null\\,\"private\":true\\,\"type\":0}\r\n"
    "X-MICROSOFT-LOCATIONS:[{\"DisplayName\":\"Microsoft Teams Meeting\"\\,\"LocationUri\r\n"
    " \":\"\"}]\r\n"
    "X-MICROSOFT-DISALLOW-COUNTER:FALSE\r\n"
    "END:VEVENT\r\n"
    "END:VCALENDAR\r\n"
)


def test_unfolding_is_a_precondition_not_a_nicety():
    """Un-unfolded, the join URL is split across physical lines and matches truncated."""
    raw_hits = rig._TEAMS_URL.findall(MICROSOFT_INVITE)
    unfolded_hits = rig._TEAMS_URL.findall(rig.unfold_ics(MICROSOFT_INVITE))
    assert JOIN not in raw_hits
    assert JOIN in unfolded_hits


def test_location_never_carries_the_join_url():
    """The single most likely wrong guess a parser author makes."""
    assert "LOCATION" not in rig.ics_teams_evidence(MICROSOFT_INVITE)["join_urls"]
    assert "LOCATION" not in rig.ics_teams_properties(MICROSOFT_INVITE)


def test_description_first_match_is_the_wrong_id():
    urls = rig.ics_teams_evidence(MICROSOFT_INVITE)["join_urls"]["DESCRIPTION"]
    assert rig.teams_native_id(urls[0]) == ("teams", "373241627805208")
    assert rig.teams_native_id(urls[-1]) == ("teams", THREAD)


def test_thread_id_comes_from_the_json_property_without_url_parsing():
    ev = rig.ics_teams_evidence(MICROSOFT_INVITE)
    assert ev["thread_id"] == THREAD
    assert ev["online_meeting_provider"] == 3  # teamsForBusiness


def test_x_property_is_the_canonical_url_and_parses_to_the_thread_id():
    props = rig.ics_teams_properties(MICROSOFT_INVITE)
    assert props["X-MICROSOFT-SKYPETEAMSMEETINGURL"] == JOIN
    assert rig.teams_native_id(props["X-MICROSOFT-SKYPETEAMSMEETINGURL"]) == ("teams", THREAD)


def test_description_url_stops_at_the_escaped_newline():
    """`\\n` inside an ICS TEXT value is a literal backslash-n; a URL character class that
    allows backslashes runs past the link into the next line's prose."""
    first = rig.ics_teams_evidence(MICROSOFT_INVITE)["join_urls"]["DESCRIPTION"][0]
    assert first.endswith("?p=HspUEOnQK2jxCFVGhg")
    assert "\\" not in first


def test_summary_reports_method_and_uid():
    s = rig.summarize_ics(MICROSOFT_INVITE)
    assert s["method"] == "REQUEST"
    assert s["dtstart"] == "20260824T162446Z"
    assert "X-MICROSOFT-SKYPETEAMSMEETINGURL" in s["properties"]


def test_non_teams_input_is_reported_as_absent_not_guessed():
    assert rig.ics_teams_evidence("") == {}
    assert rig.ics_teams_evidence("BEGIN:VCALENDAR\r\nEND:VCALENDAR\r\n") == {}
    assert rig.teams_native_id("https://meet.google.com/abc-defg-hij") is None
    assert rig.teams_native_id("") is None


def test_rfc2047_subject_decoding():
    """Exchange encodes any subject with a non-ASCII character; an em dash suffices."""
    assert rig.decode_header_text(
        "=?Windows-1252?Q?Vexa_rig_=97_ICS_property_probe?=") == "Vexa rig — ICS property probe"
    assert rig.decode_header_text("plain subject") == "plain subject"


def test_mime_calendar_parts_finds_the_text_calendar_body():
    mime = ("From: a@b.c\r\nTo: d@e.f\r\nSubject: x\r\n"
            "Content-Type: multipart/alternative; boundary=\"B\"\r\nMIME-Version: 1.0\r\n\r\n"
            "--B\r\nContent-Type: text/plain\r\n\r\nhello\r\n"
            "--B\r\nContent-Type: text/calendar; method=REQUEST\r\n\r\n"
            + MICROSOFT_INVITE + "\r\n--B--\r\n")
    parts = rig.mime_calendar_parts(mime)
    assert len(parts) == 1
    assert rig.ics_teams_evidence(parts[0])["thread_id"] == THREAD
