apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --profile cpu -f docker-compose.yml -o k8s/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: admin-api
  name: admin-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: admin-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --profile cpu -f docker-compose.yml -o k8s/
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/vexa-vexa-default: "true"
        io.kompose.service: admin-api
    spec:
      containers:
        - env:
            - name: ADMIN_API_HOST_PORT
              valueFrom:
                configMapKeyRef:
                  key: ADMIN_API_HOST_PORT
                  name: home-dima-prod-vexa-cpu--env
            - name: ADMIN_API_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: ADMIN_API_TOKEN
                  name: home-dima-prod-vexa-cpu--env
            - name: API_GATEWAY_HOST_PORT
              valueFrom:
                configMapKeyRef:
                  key: API_GATEWAY_HOST_PORT
                  name: home-dima-prod-vexa-cpu--env
            - name: BOT_IMAGE_NAME
              valueFrom:
                configMapKeyRef:
                  key: BOT_IMAGE_NAME
                  name: home-dima-prod-vexa-cpu--env
            - name: DB_HOST
              value: postgres
            - name: DB_NAME
              value: vexa
            - name: DB_PASSWORD
              value: postgres
            - name: DB_PORT
              value: "5438"
            - name: DB_USER
              value: postgres
            - name: DEVICE_TYPE
              valueFrom:
                configMapKeyRef:
                  key: DEVICE_TYPE
                  name: home-dima-prod-vexa-cpu--env
            - name: LANGUAGE_DETECTION_SEGMENTS
              valueFrom:
                configMapKeyRef:
                  key: LANGUAGE_DETECTION_SEGMENTS
                  name: home-dima-prod-vexa-cpu--env
            - name: LOG_LEVEL
              value: DEBUG
            - name: POSTGRES_HOST_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST_PORT
                  name: home-dima-prod-vexa-cpu--env
            - name: REDIS_HOST_PORT
              valueFrom:
                configMapKeyRef:
                  key: REDIS_HOST_PORT
                  name: home-dima-prod-vexa-cpu--env
            - name: REDIS_URL
              value: redis://redis:6379/0
            - name: TRAEFIK_DASHBOARD_HOST_PORT
              valueFrom:
                configMapKeyRef:
                  key: TRAEFIK_DASHBOARD_HOST_PORT
                  name: home-dima-prod-vexa-cpu--env
            - name: TRAEFIK_WEB_HOST_PORT
              valueFrom:
                configMapKeyRef:
                  key: TRAEFIK_WEB_HOST_PORT
                  name: home-dima-prod-vexa-cpu--env
            - name: TRANSCRIPTION_COLLECTOR_HOST_PORT
              valueFrom:
                configMapKeyRef:
                  key: TRANSCRIPTION_COLLECTOR_HOST_PORT
                  name: home-dima-prod-vexa-cpu--env
            - name: VAD_FILTER_THRESHOLD
              valueFrom:
                configMapKeyRef:
                  key: VAD_FILTER_THRESHOLD
                  name: home-dima-prod-vexa-cpu--env
            - name: WHISPER_MODEL_SIZE
              valueFrom:
                configMapKeyRef:
                  key: WHISPER_MODEL_SIZE
                  name: home-dima-prod-vexa-cpu--env
          image: docker.io/library/vexa-admin-api:dev
          name: admin-api
          ports:
            - containerPort: 8001
              protocol: TCP
          resources: {}
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
status: {}
