apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --profile cpu -f docker-compose.yml -o k8s/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  ports:
    - name: "8056"
      port: 8056
      targetPort: 8000
  selector:
    io.kompose.service: api-gateway
status:
  loadBalancer: {}
