apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --profile cpu -f docker-compose.yml -o k8s/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  ports:
    - name: "5438"
      port: 5438
      targetPort: 5432
  selector:
    io.kompose.service: postgres
status:
  loadBalancer: {}
