apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --profile cpu -f docker-compose.yml -o k8s/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: traefik
  name: traefik
spec:
  ports:
    - name: "9090"
      port: 9090
      targetPort: 80
    - name: "8085"
      port: 8085
      targetPort: 8080
  selector:
    io.kompose.service: traefik
status:
  loadBalancer: {}
