name: Bug report
description: Something isn't working as expected
title: "[Bug] "
labels: ["type: bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug in a few sentences
      placeholder: Describe what you saw
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      placeholder: What should have happened?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce?
      placeholder: "1. Step one\n2. Step two\n3. Step three"
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots?
      description: Paste relevant log snippets or attach screenshots
      render: shell
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Version / env?
      description: e.g. Vexa version, Docker vs bare metal, GPU/CPU, OS
      placeholder: e.g. 0.7, Docker, Ubuntu 22.04
    validations:
      required: false
