const $=id=>document.getElementById(id);let selected='';let busy=false;let catalog=[];
async function api(path,body){const r=await fetch(path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:'Request refused');return data;}
function text(tag,value){const e=document.createElement(tag);e.textContent=value;return e;}
function open(row){
 selected=row.id;const spec=catalog.find(p=>p.id===(row.provider||'fixture'));
 $('panel').hidden=false;$('label').textContent=row.label;$('secret').value='';$('panelStatus').textContent='';
 const oauth=spec.method==='oauth';$('secret').hidden=oauth;$('secretLabel').hidden=oauth;$('save').hidden=oauth;$('authorize').hidden=!oauth;
 $('authorize').disabled=!spec.configured;$('secretLabel').textContent=spec.field||'';$('permission').textContent=spec.permission;
 $('instructions').textContent=oauth?'Sign in on the provider’s website. Tokens return directly to the broker; the agent does not receive them.':'Paste the credential here. It is sent directly to the broker and never included in chat.';
 if(oauth&&!spec.configured)$('panelStatus').textContent='Provider application setup is required on this deployment. No account has been connected.';
 if(!oauth)$('secret').focus();
}
async function requestSetup(provider,label){const r=await api('/api/setup',{provider,label});await refresh();open({id:r.connection_id,label,provider});}
async function refresh(){const s=await api('/api/state');catalog=s.providers;$('operator').hidden=!s.operator;$('providers').replaceChildren();for(const p of catalog.filter(p=>p.id!=='fixture'&&!p.id.startsWith('microsoft_'))){const button=text('button',p.label);button.onclick=()=>guard(()=>requestSetup(p.id,p.label));$('providers').append(button);}$('identity').textContent=`User ${s.actor} · Session ${s.session}`;$('connections').replaceChildren();for(const c of s.connections){const card=text('div','');card.className='card';card.append(text('strong',c.label),text('small',`${c.status} · credential version ${c.version} · ${c.id}`));const setup=text('button',c.status==='ready'?(catalog.find(p=>p.id===c.provider)?.method==='oauth'?'Reconnect':'Replace key'):'Set up');setup.onclick=()=>open(c);card.append(setup);if(c.status==='ready'){const run=text('button','Verify connection');run.onclick=()=>guard(async()=>{const result=await api(`/api/connections/${c.id}/execute`,{operation_id:crypto.randomUUID(),action:c.provider==='fixture'?'fixture.verify':'connection.verify'});$('error').textContent=result.outcome==='success'?'Verified. Agent-visible result contains only status and receipt.':`Verification ${result.outcome}`;await refresh();});card.append(run);const disconnect=text('button','Disconnect');disconnect.onclick=()=>guard(async()=>{await api(`/api/connections/${c.id}/disconnect`,{});await refresh();});card.append(disconnect);} $('connections').append(card);} $('audit').replaceChildren();for(const a of s.audit){const e=text('div','');e.className='event';e.append(text('strong',`${a.action} · ${a.outcome}`),text('small',`${a.actor} / ${a.session}`),text('small',`operation ${a.operation_id||'—'} · vault ${a.vault_request_id||'—'}${a.receipt?' · receipt '+a.receipt:''}`));$('audit').append(e);}const want=new URLSearchParams(location.hash.slice(1)).get('connection');if(want&&!selected){const row=s.connections.find(c=>c.id===want);if(row)open(row);}}
async function guard(fn){if(busy)return;busy=true;try{await fn();}catch(e){$('error').textContent=e.message;}finally{busy=false;}}
$('request').onclick=()=>guard(()=>requestSetup('fixture','Test API connection'));
$('authorize').onclick=()=>guard(async()=>{const r=await api(`/api/connections/${selected}/authorize`,{});location.assign(r.authorize_url);});
$('close').onclick=()=>{$('secret').value='';$('panel').hidden=true;selected='';};
$('save').onclick=()=>guard(async()=>{const value=$('secret').value;$('secret').value='';await api(`/api/connections/${selected}/secret`,{value});$('panelStatus').textContent='Stored in OpenBao. No secret returned to the agent.';await refresh();});
guard(async()=>{const params=new URLSearchParams(location.hash.slice(1));const token=params.get('login');if(token){history.replaceState(null,'','/');await api('/login',{value:token});}await refresh();});

$('configureGoogle').onclick=()=>guard(async()=>{const client_id=$('clientId').value.trim(),client_secret=$('clientSecret').value.trim();$('clientSecret').value='';await api('/api/operator/google',{client_id,client_secret});$('configStatus').textContent='Application stored in OpenBao.';await refresh();});
