"""desk_readme.py — the desk README as a HUB OF LINKS: what this person generally needs, one click away.

Founder, 2026-09-02: *"we want the personal desk readme to be the thing where they have what they
generally need — mostly links to the other cards in different workspaces."*

That is a sharper instruction than "show what is on the desk", and it changes three things. The page
is **links, not prose** — two lines of header and then nothing but cards. The cards come from **every
mounted workspace**, not just this one, each linked into whichever workspace actually holds it. And
the ordering is by **use**, not by recency of writing: ranking by last-modified ranks by what the
AGENT touched, which is close to the opposite of what the person wants at the top — the page the
agent just wrote is the one they have not read yet.

The page, in order:

    # <name> — desk                  two lines of prose, written once, never regenerated
    ## Pinned                        THEIRS. Hand-edited, never touched by this module.
    ## Now                           next meetings (<=5) + dated open commitments (<=10)
    ## People / Companies / Projects most-used first, <=12 each, across workspaces
    ## Workspaces                    the groups they are in, id-linked
    ## Recently opened               the last 10 pages they actually opened

Every generated section lives between markers::

    <!-- desk:people:start -->  … regenerated …  <!-- desk:people:end -->

**Nothing outside the markers is ever touched, and `## Pinned` is inside markers precisely so that
it is never touched either** — it is written once, empty, with a one-line hint, and after that it is
the person's. A section a human edits needs a fence around it more than a generated one does: the
generator has to know where to stop.

WHAT WAS DROPPED. `## Meetings`, `## Open commitments` and `## Next dates` were three lists of the
same question ("what is coming"); they are one `## Now`. Purpose / Objective / Where-things-stand
belong to a GROUP's README — a group has a purpose, a desk is a person. Their markers are removed on
sight so a desk generated by the earlier shape converges instead of carrying dead blocks forever.

LINK FORM. A card in ANOTHER mounted workspace is `[[ws:<workspace-id>/<entity-id>]]`, so the link
survives that workspace being renamed and renders its title at read time (PRD decision 26.2). A card
on THIS desk stays `[[Title]]` — the in-workspace form, unchanged, and writing an id form for the
workspace the file is already in would be a redirection through an id for no gain.
"""
from __future__ import annotations

import datetime as _dt
import re
from pathlib import Path
from typing import Iterable, Optional

from shared.entities import ENTITIES_DIR, KINDS, split_frontmatter
from shared.links import format_ref

README = "README.md"

# key → heading, in page order. `pinned` leads because it is the person's own, and a hand-edited
# section that anything is written above reads as though the product moved it.
SECTIONS: tuple[tuple[str, str], ...] = (
    ("pinned", "Pinned"),
    ("now", "Now"),
    ("people", "People"),
    ("companies", "Companies"),
    ("projects", "Projects"),
    ("workspaces", "Workspaces"),
    ("recent", "Recently opened"),
)

# THE ONE SECTION THIS MODULE WRITES ONCE AND NEVER AGAIN. Its marker exists so the generator knows
# where the person's text begins and ends — a fence around a human's writing, not around ours.
HAND_EDITED = frozenset({"pinned"})

# Retired shapes, removed on sight so a desk generated by the earlier version converges rather than
# carrying dead blocks. Their content is in `## Now` and in the group READMEs where it belongs.
RETIRED_SECTIONS = ("meetings", "commitments", "dates", "purpose", "objective", "where")

_MARKER = "<!-- desk:{key}:{edge} -->"

MEETINGS_MAX = 5
COMMITMENTS_MAX = 10
CARDS_MAX = 12
RECENT_MAX = 10

# Which entity kinds each card section lists. `meeting` and `decision` are not sections of their
# own: a meeting is in `## Now` while it is ahead and in the card it belongs to afterwards.
CARD_KINDS = {"people": "person", "companies": "company", "projects": "project"}

_COMMIT_HEADING = re.compile(r"^#{1,6}\s*(committed|commitments|open items?|action items?|next steps?)\b",
                             re.I | re.M)
_HEADING = re.compile(r"^#{1,6}\s", re.M)
_BULLET = re.compile(r"^\s*[-*]\s+(.+?)\s*$", re.M)
_ISO_DATE = re.compile(r"\b(\d{4}-\d{2}-\d{2})\b")
_DATED_HEADING = re.compile(r"^##\s+(\d{4}-\d{2}-\d{2})\s*$", re.M)
_SOURCE_SUFFIX = re.compile(r"\s+—\s+source:\s.*$")
_FM_DATE_KEYS = ("date", "when", "scheduled", "starts", "start")


def _marker(key: str, edge: str) -> str:
    return _MARKER.format(key=key, edge=edge)


# ── the cards, across every mounted workspace ────────────────────────────────────────────────────

class Card:
    """One entity page, wherever it lives. The unit every section is made of."""

    __slots__ = ("kind", "title", "slug", "path", "workspace", "home", "text", "when", "modified")

    def __init__(self, *, kind, title, slug, path, workspace, home, text, when, modified):
        self.kind, self.title, self.slug, self.path = kind, title, slug, path
        self.workspace, self.home, self.text = workspace, home, text
        self.when, self.modified = when, modified

    @property
    def link(self) -> str:
        """`[[Title]]` on this desk; `[[ws:<id>/<entity-id>]]` anywhere else."""
        return f"[[{self.title}]]" if self.home else format_ref(self.workspace, self.slug)

    @property
    def member(self) -> str:
        """How a touch names this page: `<workspace id>/<path>`."""
        return f"{self.workspace}/{self.path}"


def _fm(lines: list[str], key: str) -> Optional[str]:
    for ln in lines:
        k, sep, v = ln.partition(":")
        if sep and k.strip() == key:
            return v.split("#")[0].strip()
    return None


def _card_when(fm: list[str], text: str, title: str) -> Optional[str]:
    """The date this card is ABOUT — a meeting's own date, not when it was written.

    Frontmatter first (`date`/`when`/`scheduled`), then the title (meeting pages are named
    `DNA TSC 2026-03-16`), then the earliest ISO date in the body. Dated entry headings are
    excluded: those are when somebody wrote, which is the signal this deliberately is not."""
    for key in _FM_DATE_KEYS:
        v = _fm(fm, key)
        if v and _ISO_DATE.search(v):
            return _ISO_DATE.search(v).group(1)
    m = _ISO_DATE.search(title or "")
    if m:
        return m.group(1)
    body = _DATED_HEADING.sub(" ", text or "")
    found = sorted(set(_ISO_DATE.findall(body)))
    return found[0] if found else None


def cards(mounts: Iterable[dict], home_id: str) -> list[Card]:
    """Every entity page in every mounted workspace, as cards.

    A mount with no workspace id is skipped: nothing can be linked into it yet, and a card whose
    link cannot be written is worse on this page than a card that is absent — a hub of links whose
    links do not resolve is not a hub."""
    out: list[Card] = []
    for m in mounts or []:
        if not isinstance(m, dict):
            continue
        wid = str(m.get("id") or "")
        root = Path(str(m.get("path") or ""))
        if not wid or not root.is_dir():
            continue
        for kind in KINDS:
            d = root / ENTITIES_DIR / kind
            if not d.is_dir():
                continue
            for f in sorted(d.glob("*.md")):
                if f.name == "index.md":
                    continue
                try:
                    text = f.read_text(encoding="utf-8", errors="replace")
                    modified = f.stat().st_mtime
                except OSError:
                    continue
                fm, _ = split_frontmatter(text)
                if (_fm(fm, "template") or "").lower() == "true":
                    continue          # a SHAPE is never a card
                title = _fm(fm, "title") or f.stem
                out.append(Card(kind=kind, title=title, slug=f.stem,
                                path=f"{ENTITIES_DIR}/{kind}/{f.name}", workspace=wid,
                                home=(wid == home_id), text=text,
                                when=_card_when(fm, text, title), modified=modified))
    return out


def _last_written(text: str, modified: float) -> float:
    """When this page was last written, as an epoch — the FALLBACK ranking signal."""
    days = _DATED_HEADING.findall(text or "")
    if days:
        try:
            return _dt.datetime.fromisoformat(max(days)).timestamp()
        except ValueError:
            pass
    return modified


def _rank(card: Card, touched: dict) -> float:
    """The usage signal: whichever of "last opened" and "last written" is more recent.

    Opening beats writing when both exist, because it is the only one of the two the PERSON did —
    but writing still counts, so a desk whose panel has never reported a view still ranks something
    sensible rather than everything alphabetically."""
    return max(touched.get(card.member, 0.0), _last_written(card.text, card.modified))


# ── the sections ─────────────────────────────────────────────────────────────────────────────────

def _now_rows(cards_: list[Card], today: str) -> list[str]:
    """What is ahead: meetings, then dated commitments. One line per link, date first."""
    ahead = sorted((c for c in cards_ if c.kind == "meeting" and c.when and c.when >= today),
                   key=lambda c: c.when)[:MEETINGS_MAX]
    rows = [f"- {c.when} — {c.link}" for c in ahead]

    dated: list[tuple[str, str]] = []
    for c in cards_:
        for m in _COMMIT_HEADING.finditer(c.text):
            nxt = _HEADING.search(c.text, m.end())
            for b in _BULLET.findall(c.text[m.end(): nxt.start() if nxt else len(c.text)]):
                line = _SOURCE_SUFFIX.sub("", b).strip()
                day = next((d for d in sorted(_ISO_DATE.findall(line)) if d >= today), None)
                if day and line:
                    dated.append((day, f"- {day} — {line} — {c.link}"))
    rows += [row for _d, row in sorted(dated)[:COMMITMENTS_MAX]]
    return rows


def _card_rows(cards_: list[Card], kind: str, touched: dict) -> list[str]:
    picked = sorted((c for c in cards_ if c.kind == kind), key=lambda c: _rank(c, touched), reverse=True)
    return [f"- {c.link}" for c in picked[:CARDS_MAX]]


def _workspace_rows(workspaces: Iterable[dict]) -> list[str]:
    """The groups this person is in, id-linked to each group's README.

    An id-link and not a name: a group gets renamed, and the whole reason this section exists on the
    desk is to be the door that still opens afterwards."""
    return [f"- {format_ref(str(w['id']), README)}"
            for w in (workspaces or []) if isinstance(w, dict) and str(w.get("id") or "").strip()]


def _recent_rows(touches: list[dict], cards_: list[Card], home_id: str) -> list[str]:
    """The last pages this person actually opened, across workspaces.

    A touch that matches a card renders as that card (so the row says a name, not a path); one that
    does not — a note, a README, a file with no entity id — renders as a path link, which is the
    form decision 26.2 keeps for exactly this case."""
    by_member = {c.member: c for c in cards_}
    rows: list[str] = []
    for t in touches[:RECENT_MAX]:
        wid, path = str(t.get("workspace") or ""), str(t.get("path") or "")
        if not wid or not path:
            continue
        card = by_member.get(f"{wid}/{path}")
        if card is not None:
            rows.append(f"- {card.link}")
        elif wid == home_id:
            rows.append(f"- `{path}`")
        else:
            rows.append(f"- {format_ref(wid, path)}")
    return rows


PINNED_HINT = ("<!-- Yours. Put the links you want at the top of your desk here — nothing below "
               "this section is hand-edited, and nothing in it is ever regenerated. -->")


def render_sections(root, *, mounts: Iterable[dict] = (), workspaces: Iterable[dict] = (),
                    touches: Optional[list] = None, home_id: str = "",
                    today: Optional[str] = None) -> dict:
    """`{key: body}` — the generated body of every section, headings included."""
    day = today or _dt.date.today().isoformat()
    mounts = list(mounts or [])
    if not mounts:
        mounts = [{"path": str(root), "id": home_id}]
    all_cards = cards(mounts, home_id)
    touched = {f"{t.get('workspace')}/{t.get('path')}": float(t.get("at") or 0)
               for t in (touches or []) if isinstance(t, dict)}

    def block(heading: str, rows: list[str], empty: str) -> str:
        head = f"## {heading}\n"
        if not rows:
            return head + f"\n_{empty}_\n"
        return head + "\n" + "\n".join(rows) + "\n"

    return {
        "pinned": f"## Pinned\n\n{PINNED_HINT}\n",
        "now": block("Now", _now_rows(all_cards, day),
                     f"Nothing scheduled or committed on or after {day}."),
        "people": block("People", _card_rows(all_cards, "person", touched),
                        "No people on this desk yet."),
        "companies": block("Companies", _card_rows(all_cards, "company", touched),
                           "No companies on this desk yet."),
        "projects": block("Projects", _card_rows(all_cards, "project", touched),
                          "No projects on this desk yet."),
        "workspaces": block("Workspaces", _workspace_rows(workspaces),
                            "This desk belongs to no group workspace yet."),
        "recent": block("Recently opened", _recent_rows(touches or [], all_cards, home_id),
                        "Nothing opened from here yet."),
    }


# ── writing it, without ever touching what is not ours ───────────────────────────────────────────

def _replace_marked(text: str, key: str, body: str) -> tuple[str, bool]:
    start, end = _marker(key, "start"), _marker(key, "end")
    i, j = text.find(start), text.find(end)
    if i == -1 or j == -1 or j < i:
        return text, False
    return text[: i + len(start)] + "\n" + body.strip("\n") + "\n" + text[j:], True


def _drop_marked(text: str, key: str) -> str:
    """Remove a retired section entirely, markers and all."""
    start, end = _marker(key, "start"), _marker(key, "end")
    i, j = text.find(start), text.find(end)
    if i == -1 or j == -1 or j < i:
        return text
    return (text[:i].rstrip("\n") + "\n\n" + text[j + len(end):].lstrip("\n")).strip("\n") + "\n"


def header_for(name: str = "") -> str:
    """Two lines of prose, and that is the whole allowance.

    Written ONCE, above the markers, and never regenerated — the moment the agent has something
    better to say at the top of somebody's desk it says it, and this is out of the way."""
    who = (name or "").strip()
    return (f"# {who} — desk\n" if who else "# This desk\n") + \
        "\nThe view over the files, never a second source of truth.\n"


def update_readme(root, *, mounts: Iterable[dict] = (), workspaces: Iterable[dict] = (),
                  touches: Optional[list] = None, home_id: str = "", name: str = "",
                  today: Optional[str] = None) -> dict:
    """Regenerate the desk README's marked sections. Returns `{path, changed, sections}`.

    Idempotent: a desk whose cards and touches have not moved rewrites byte-identical content and
    reports `changed: False`, so this is safe to run at the end of every turn."""
    p = Path(root) / README
    try:
        before = p.read_text(encoding="utf-8", errors="replace")
    except OSError:
        before = ""
    text = before
    for key in RETIRED_SECTIONS:
        text = _drop_marked(text, key)
    sections = render_sections(root, mounts=mounts, workspaces=workspaces, touches=touches,
                               home_id=home_id, today=today)
    appended: list[str] = []
    for key, _heading in SECTIONS:
        found = _marker(key, "start") in text and _marker(key, "end") in text
        if found and key in HAND_EDITED:
            continue                      # theirs — the fence is what tells us to stop here
        if found:
            text, _ = _replace_marked(text, key, sections[key])
        else:
            appended.append(f"{_marker(key, 'start')}\n{sections[key].strip()}\n{_marker(key, 'end')}")
    if appended:
        head = text.rstrip("\n") or header_for(name).rstrip("\n")
        text = head + "\n\n" + "\n\n".join(appended) + "\n"
    if text != before:
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text, encoding="utf-8")
    return {"path": README, "changed": text != before, "sections": [k for k, _ in SECTIONS]}
