#!/usr/bin/env node
/**
 * arch-dsl.mjs — a DETERMINISTIC text projection of architecture.calm.json (the LLM-context view).
 *
 * CALM JSON is the sealed source of truth (gate:dataflow), but it's ~8k tokens of mostly structural
 * boilerplate — poor to read raw. This emits the same facts as a compact edge-list DSL (~1.3k tokens),
 * so an agent always has the whole-graph index in context without rendering SVG or parsing the JSON.
 * Pure function of the model: sorted + stable, every output token traceable to a CALM field, no dates.
 *
 *   node scripts/arch-dsl.mjs                 # print the DSL to stdout
 *   node scripts/arch-dsl.mjs --out=PATH      # write it to PATH (default docs/views/architecture.dsl)
 *   node scripts/arch-dsl.mjs --write         # write to the default path
 *   node scripts/arch-dsl.mjs --check         # exit 1 if the committed file != freshly generated (anti-drift)
 *
 * It is GENERATED, never hand-edited. `pnpm seal:arch` regenerates it; the anti-drift check keeps it honest.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";

const ROOT = process.cwd();
const SRC = join(ROOT, "architecture.calm.json");
const DEFAULT_OUT = join(ROOT, "docs", "views", "architecture.dsl");

const args = process.argv.slice(2);
const flag = (k, d) => { const a = args.find((x) => x.startsWith(`--${k}=`)); return a ? a.split("=")[1] : d; };
const has = (k) => args.includes(`--${k}`);

function render() {
  const M = JSON.parse(readFileSync(SRC, "utf8"));
  const nodes = [...(M.nodes || [])].sort((a, b) => a["unique-id"].localeCompare(b["unique-id"]));
  const rels = M.relationships || [];
  const flows = M.flows || [];
  const byId = new Map(nodes.map((n) => [n["unique-id"], n]));
  const metaOf = (n, k) => (n.metadata || []).map((m) => m[k]).find((v) => v !== undefined);
  const relMeta = (r, k) => (r.metadata || []).map((m) => m[k]).find((v) => v !== undefined);

  const L = [];
  L.push("# architecture.calm.json — edge-list DSL (GENERATED by scripts/arch-dsl.mjs; DO NOT EDIT)");
  L.push("# source of truth: architecture.calm.json (sealed, gate:dataflow) · regenerate: pnpm arch:dsl");
  L.push("");

  // nodes
  L.push("## nodes  (id [type] @path)");
  for (const n of nodes) {
    const p = metaOf(n, "path");
    L.push(`${n["unique-id"]} [${n["node-type"]}]${p ? " @" + p : ""}`);
  }
  L.push("");

  // composition (container > sorted children)
  L.push("## composition  (container > children)");
  const comp = rels
    .filter((r) => r["relationship-type"]?.["composed-of"])
    .map((r) => r["relationship-type"]["composed-of"])
    .sort((a, b) => a.container.localeCompare(b.container));
  for (const c of comp) L.push(`${c.container} > ${[...c.nodes].sort().join(", ")}`);
  L.push("");

  // connects (src -access-> dst [contract]) — sorted lines
  L.push("## connects  (src -access-> dst [contract])");
  const edges = rels
    .filter((r) => r["relationship-type"]?.connects)
    .map((r) => {
      const c = r["relationship-type"].connects;
      const acc = relMeta(r, "access") || "?";
      const ctr = relMeta(r, "contract");
      return `${c.source.node} -${acc}-> ${c.destination.node}${ctr ? " [" + ctr + "]" : ""}`;
    })
    .sort();
  for (const e of edges) L.push(e);
  L.push("");

  // carriers (single-writer ownership)
  L.push("## carriers  (id <= writers · op · stage)");
  for (const n of nodes) {
    const own = n.controls?.ownership;
    if (!own) continue;
    const cfg = own.requirements?.[0]?.config || {};
    const stage = metaOf(n, "stage");
    L.push(`${n["unique-id"]} <= ${(cfg.writers || []).join("+")} · ${cfg.op || "?"}${stage ? " · " + stage : ""}`);
  }
  L.push("");

  // flows (id: ordered transitions)
  L.push("## flows  (id: step. edge — description)");
  for (const f of [...flows].sort((a, b) => a["unique-id"].localeCompare(b["unique-id"]))) {
    L.push(`${f["unique-id"]} — ${f.name || ""}`);
    for (const t of [...f.transitions].sort((a, b) => (a["sequence-number"] || 0) - (b["sequence-number"] || 0))) {
      L.push(`  ${t["sequence-number"]}. ${t["relationship-unique-id"]} — ${t.description || ""}`);
    }
  }
  return L.join("\n") + "\n";
}

const dsl = render();

if (has("check")) {
  const out = flag("out", DEFAULT_OUT);
  const have = existsSync(out) ? readFileSync(out, "utf8") : "";
  if (have !== dsl) {
    console.error(`✗ arch:dsl — ${out} is stale. Run \`pnpm arch:dsl --write\` (it is generated, never hand-edited).`);
    process.exit(1);
  }
  console.log(`✓ arch:dsl — ${out} matches architecture.calm.json`);
  process.exit(0);
}

if (has("write") || flag("out", null)) {
  const out = flag("out", DEFAULT_OUT);
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, dsl);
  console.log(`✓ arch:dsl — wrote ${out} (${dsl.length} bytes)`);
} else {
  process.stdout.write(dsl);
}
